### ISSUE TITLE
setup Issue

### ISSUE THREAD

**Issue by darshantumkur** [envoyproxy/java-control-plane#123]
I tried to set up java-control-plane on my local machine;
`Cloned and $ mvn clean package`

The Build is successful but IntelliJ fails to recognize 
`import io.envoyproxy.envoy.api.v2.DiscoveryResponse;`

Am I missing anything?

> [INFO] Reactor Summary:
> [INFO] 
> [INFO] java-control-plane ................................. SUCCESS [  4.516 s]
> [INFO] api ................................................ SUCCESS [04:44 min]
> [INFO] cache .............................................. SUCCESS [ 14.967 s]
> [INFO] server ............................................. SUCCESS [ 19.204 s]
> [INFO] test ............................................... SUCCESS [  0.504 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS

**Comment by slonka** [comment]
The current codebase works with Intellij CE 2020. Closing, if this happens again please reopen.
