### ISSUE TITLE
Possible race condition when RDS might be sent before LDS

### ISSUE THREAD

**Issue by lukidzi** [envoyproxy/java-control-plane#134]
It possible that RDS might be sent before LDS. When there is many changes in state of application it might happens that RDS watch will be answeared in `createWatch` with new version. 

E.g.:
1. Envoy connects to control-plane
2. Snapshot already exists in control-plane <- other instance share same group
3. Control-plane respond with LDS in createWatch method
4. There is snapshot update which change LDS and RDS versions
5. Envoy sends RDS request
6. Control-plane respond with RDS in createWatch method
7. Envoy resume LDS and RDS requests.
8. Envoy sends request LDS
9. Control plane respond with LDS in createWatch method (new version)
10. Envoy sends RDS requests
11. Control plane doesn't respond because version hasn't changed
12. Listeners of a service stays in warming phase

**Comment by slonka** [comment]
Merged PRs seem to indicate that this is fixed, if I'm mistaken please reopen.
