### ISSUE TITLE
Is there a way to publish Envoy configuration without SimpleCache.setSnapshot?

### ISSUE THREAD

**Issue by mabukhovsky** [envoyproxy/java-control-plane#136]
Hi guys, I'm using ControlPlane to build complex Envoy configurations with thousands of routes & clusters. I've discovered that after SimpleCache.setSnapshot call huge configuration remains in the memory (100MB or even more) as the following maps are keeping config & statuses:

```
private final Map<T, Snapshot> snapshots = new HashMap<>();
private final Map<T, CacheStatusInfo<T>> statuses = new HashMap<>();
```

Is there a way to publish Envoy configuration without SimpleCache? I would like to build snapshot and push it to Envoy config dump and do not leave any 'big' traces in RAM.

**Comment by jakubdyszkiewicz** [comment]
I think you could implement either your `SnapshotCache` or even `ConfigWatcher` that would always construct the response from scratch. Depending on your use case you have to be careful with such a strategy:
1) Cache can help you segment the configs for the same Envoys (for example multiple instances of the same service), so you won't have to construct the config many times
2) Cache protects you against downtime of your discovery source (assuming that you construct configs based on data from some other system)
3) In case of massive Envoy restarts, you will be seeing a heavy load on your control plane.

It would be interesting to hear more about your use case.

**Comment by mabukhovsky** [comment]
Thank you for detailed explanation. It all makes sense. I've decided to keep using the cache as it is.
