### ISSUE TITLE
ratelimit DescriptorStatus does not implement duration_until_reset defined in data plane api

### ISSUE THREAD

**Issue by wwillsey** [envoyproxy/java-control-plane#146]
Please see:
https://github.com/envoyproxy/java-control-plane/blob/master/api/src/main/proto/envoy/service/ratelimit/v3/rls.proto#L95
whereas, in the envoy data plane api, the rls.proto defines:
https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/ratelimit/v3/rls.proto#L117

Is this a bug? or was this value intentionally left out?

**Comment by jakubdyszkiewicz** [comment]
I'm pretty sure that is the result of unsynced proto files. We need to update proto files to catch up with Envoy changes

**Comment by nezdolik** [comment]
+1 on this. I have wip PR for upgrading v3 cluster proto to latest version: https://github.com/envoyproxy/java-control-plane/pull/148 (will prioritise for next week).

**Comment by slonka** [comment]
`duration_until_reset` was recently updated: https://github.com/envoyproxy/java-control-plane/blame/master/api/src/main/proto/envoy/service/ratelimit/v3/rls.proto#L117. Closing this issue, if there is something missing please reopen.
