### ISSUE TITLE
not able to run TestMain.java

### ISSUE THREAD

**Issue by madhukkc** [envoyproxy/java-control-plane#165]
Hi i trield downloading java control plane
rand the proto updates
compiled the project using mvn clean package and was able to compile .
However, when i try to import  and run this in eclipse, i  see many compilation issues and not able to run the TestMain.

Especailly i see issues with "AutoValue_LatestDiscoveryResponse" and many "Auto_XXx" classes.
not sure what i am missing.

**Comment by madhukkc** [comment]
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	AutoValue_Snapshot cannot be resolved to a type

	at io.envoyproxy.controlplane.cache.v2.Snapshot.create(Snapshot.java:48)
	at io.envoyproxy.controlplane.server.TestMain.main(TestMain.java:41)

**Comment by slonka** [comment]
Are you sure you've built the project? Try running "mvn package" to make sure all the class are compiled. It works on main branch on my intellij setup

![image](https://user-images.githubusercontent.com/2753650/119506768-85932f80-bd6e-11eb-85b2-524df80f9d8c.png)
