### ISSUE TITLE
Implement Backoff strategy when config update fails

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/java-control-plane#17]
When config update fails at envoy, currently we are just logging (as per https://github.com/envoyproxy/java-control-plane/pull/14) the error and sending the same response again. It is likely to fail again immediately based on kind of error we get. Ideally based on error we should be able to decide whether to send the request again or not. However, we should at least implement some backoff strategy or rate limiting these failed responses.

**Comment by slonka** [comment]
We've implemented rate limiting on the Envoy's side. Maybe @pbetkier can share some thoughts on implementing this on CP side.

**Comment by pbetkier** [comment]
IMO this is no longer relevant, we concluded DDoS prevention in #101 a year later. @ramaraochavali was helpfully participating in that discussion and he actually authored the Envoy solution https://github.com/envoyproxy/envoy/pull/4719. Seems enough for now.
