### ISSUE TITLE
[question | help wanted] xDS data-plane hello world

### ISSUE THREAD

**Issue by adalrsjr1** [envoyproxy/java-control-plane#216]
how can I implement a hello-world for a xDS data-plane? any examples available?

I'm trying to prototype a Java data-plane to work with Istio for a research, and I'm struggling with the very initial step. How can I stablish the initial connection with the control-plane and start listening for changes? I'm aware about the Envoy's xDS spec. My questions are more related to the machinery that I have to put together.

I looked for some tests to help me how to bootstrap this prototype, but I didn't get sense of which would be the best example to follow.

**Comment by liangyuanpeng** [comment]
Use this repo to implement your grpc service and then config envoy for XDS.
