### ISSUE TITLE
Request monitoring hooks

### ISSUE THREAD

**Issue by snowp** [envoyproxy/java-control-plane#24]
In order to be able to monitor the config changes (and alert on updates stuck due to NACK loops) it'd be nice to have some hooks in `DiscoveryServer` to let us observe the result. Something generic like a callback that just receives the request object whenever one is sent would be sufficient for our use cases, but I'm open to other options.

**Comment by ramaraochavali** [comment]
@snowp just to get more details, what would you like to do when request failed in the callback? Would you want an ability to suggest `DiscoveryServer` what it should do next - like ignore this failure, retry etc?

**Comment by joeyb** [comment]
@snowp - Does #35 cover what you're looking for here, or would it need to be expanded further to fit your use case?

**Comment by snowp** [comment]
Yep, it does exactly what I wanted. I'll close this out. Thanks!
