### ISSUE TITLE
Clean up proto build() noise

### ISSUE THREAD

**Issue by snowp** [envoyproxy/java-control-plane#4]
(Basing this on #2)

Noticed quite a bit of redundant calls to `.build()` when making non-trivial proto messages: protoc generates an overload that accepts a `Message.Builder` instead of a `Message` when setting fields on a proto builder.  This allows you to omit the `build()` when passing a proto to a setter. 

I noticed this in `server/src/test/java/io/envoyproxy/controlplane/server/Resources.java`, but there might be other occurrences. 

This tracks cleaning that up, as it just adds noise to the code.

**Comment by joeyb** [comment]
Since the initial migration in #2 hasn't been merged yet, I went ahead and pushed an additional commit that drops those superfluous `.build()` calls. I'll mark this as closed, but let me know if you see any that I missed. Thanks!
