### ISSUE TITLE
TCP Proxy's route not implementes yet ?

### ISSUE THREAD

**Issue by leader-us** [envoyproxy/java-control-plane#67]
* <pre>
     * TCP Proxy filter configuration using deprecated V1 format. This is required for complex
     * routing until filter chain matching in the listener is implemented.
     * .. attention::
     *   Using this field will lead to `problems loading the configuration
     *   &lt;https://github.com/envoyproxy/envoy/issues/2441&gt;`_. If you want to configure the filter
     *   using v1 config structure, please make this field a boolean with value ``true`` and configure
     *   via the opaque ``value`` field like is suggested in :api:`envoy/config/filter/README.md`.
     * </pre>
     *
     * <code>.envoy.config.filter.network.tcp_proxy.v2.TcpProxy.DeprecatedV1 deprecated_v1 = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public envoy.config.filter.network.tcp_proxy.v2.TcpProxyOuterClass.TcpProxy.DeprecatedV1OrBuilder getDeprecatedV1OrBuilder() {
      return getDeprecatedV1();
    }

so the following code can't work ?

envoy.config.filter.network.tcp_proxy.v2.TcpProxyOuterClass.TcpProxy.Builder tcpProxyBuilder=envoy.config.filter.network.tcp_proxy.v2.TcpProxyOuterClass.TcpProxy.newBuilder();
		envoy.config.filter.network.tcp_proxy.v2.TcpProxyOuterClass.TcpProxy.DeprecatedV1.Builder routeBuiler=tcpProxyBuilder.setStatPrefix("ingress_tcp").getDeprecatedV1Builder();
		routeBuiler.addRoutes(value)

**Comment by snowp** [comment]
I this still an issue? The latest release should have bumped the version to write that config
