### ISSUE TITLE
Package io.envoyproxy.envoy missing in class TestMain

### ISSUE THREAD

**Issue by rinormaloku** [envoyproxy/java-control-plane#97]
After pulling the source code and executing: 

```
mvn clean package 
```

In the test class `TestMain` the following files fail to import:

```
import io.envoyproxy.envoy.api.v2.Cluster;
import io.envoyproxy.envoy.api.v2.Cluster.DiscoveryType;
import io.envoyproxy.envoy.api.v2.core.Address;
import io.envoyproxy.envoy.api.v2.core.SocketAddress;
```

Tested this on Windows and Ubuntu. The same end result.

**Comment by jakubdyszkiewicz** [comment]
Just tested on MacOS Mojave and Maven 3.6.0 and it works.
Can you paste the output from the Maven? I assume the problem is that there was a problem from generation classes from proto.

**Comment by rinormaloku** [comment]
Hi @jakubdyszkiewicz,

Just got time to get back on this. Works perfectly, I most likely messed sth. 

For someone who might have a similar issue, I fixed it by cloning once again and starting the command manually from the terminal, instead of from an IDE.
